### ISSUE TITLE
Please consider fixing type annotations

### ISSUE THREAD

**Issue by NeilGirdhar** [Marco-Sulla/python-frozendict#39] opened 2021-12-16 19:44 UTC
It appears that there are some missing files:
```python
from frozendict import frozendict  # error: Library stubs not installed for "frozendict" (or incompatible with Python 3.10)
reveal_type(dict.fromkeys("abc", 0))  # Revealed type is "builtins.dict[builtins.str*, builtins.int*]"
reveal_type(frozendict.fromkeys("abc", 0))  # Revealed type is "Any"
```
If you want type annotations to work, you could consider
- exposing a py.typed file so that static typing is enabled,
- annotating the methods in core.py, which should be easy now that Python 3.6 is (almost) dead.

**Comment by Marco-Sulla** [comment] 2021-12-22 17:43
I have no knowledge about this. If you want to create a PR, I can consider it :)

**Comment by peku33** [comment] 2022-01-17 17:57
In the current design the frozendict inherits from `dict` which is not typed in python 3.8 but typed in python 3.9.
It is not possible to use `frozendict[K, V]` in 3.8, while the same is valid for 3.9.
Users in 3.8 currently can use `typing.Dict` approach. Is there similar typed frozendict version compatible with 3.8?

**Comment by NeilGirdhar** [comment] 2022-01-17 18:11
@peku33 Where are you finding `frozendict[K, V]`?

**Comment by peku33** [comment] 2022-01-17 18:22
In my code. `frozendict[K, V]` is correctly recognized by python 3.10, mypy, pylance etc.
When put inside class / dataclass definition - types are hinted properly.

**Comment by NeilGirdhar** [comment] 2022-01-17 18:26
@peku33 I see because `frozendict` inherits from `dict`, and `dict` defines `class_getattr`.  Well, that would be unaffected by this issue, which merely asks for the additional methods to be annotated.

**Comment by Marco-Sulla** [comment] 2022-01-17 18:27
> In the current design the frozendict inherits from `dict` 

Well, this is true for the pure Py version, not for the C extension, that is the default from version 2.2.0 (the current one).

> Users in 3.8 currently can use `typing.Dict` approach. Is there similar typed frozendict version compatible with 3.8?

I think I can add it. The problem is I really don't know how. I admit I never used type hinting. I have to study.

**Comment by peku33** [comment] 2022-01-17 18:29
I think for python below 3.9 (which introduces the typed `dict`) (and possibly higher then 3.6?) the base class should be `typings.Dict`, not `dict`.

This can possibly be done with `if sys.version_info < (3, 9):` or somethign similar.

**Comment by NeilGirdhar** [comment] 2022-01-17 18:32
> I think I can add it. The problem is I really don't know how. I admit I never used type hinting. I have to study.

Why would you add it?  `frozendict` is not a dict.  If you're going to add something, just inherit from `Mapping[K, V]` and `Generic[K, V]`.  Then you'll satisfy his annotations without promising all kinds of things that you don't support.

>  the base class should be typings.Dict, not dict.

No it should not.  A frozendict is not a dict.

**Comment by peku33** [comment] 2022-01-17 18:35
Yes, thing like Mapping is probably fine. I thought the implementation relies on dict underneath and just shadows some methods.

The goal is to have typed declaration in class / function footprint with typed methods etc.

**Comment by NeilGirdhar** [comment] 2022-01-17 18:37
> Well, this is true for the pure Py version, not for the C extension, that is the default from version 2.2.0 (the current one).

As far as the annotations go, it's true for both versions I imagine.

**Comment by Marco-Sulla** [comment] 2022-01-17 18:41
> Yes, thing like Mapping is probably fine. I thought the implementation relies on dict underneath and just shadows some methods.

This is true for the python implementation, not for the C Extension. `frozendict` in the C Extension inherits only from `Mapping` and `object`, and has some methods optimized for the speed. Sometime it's faster than dict.

> The goal is to have typed declaration in class / function footprint with typed methods etc.

I agree.

**Comment by lurch** [comment] 2022-08-14 11:59
I know nothing about mypy and type annotations, but does #62 also fix this issue? :shrug:

**Comment by Marco-Sulla** [comment] 2022-08-14 17:58
> I know nothing about mypy and type annotations, but does #62 also fix this issue? shrug

No.

**Comment by Marco-Sulla** [comment] 2023-02-18 20:36
Currently, annotations can be enabled by merging https://github.com/Marco-Sulla/python-frozendict/pull/70 , but I need to add some tests before and I don't know where to start.

**Comment by ydirson** [comment] 2023-02-25 19:03
With version 2.3.5, all uses of the `frozendict` type trigger a mypy `error: Module not callable`: looks like something confuses mypy into thinking we're accessing the module, when we're accessing the same-name type from that module.

**Comment by Marco-Sulla** [comment] 2023-02-25 19:15
@ydirson steps to reproduce?

**Comment by ydirson** [comment] 2023-02-25 21:28
Testing this code in a brand new venv with latest frozendict and mypy:
```
from frozendict import frozendict

d = frozendict(a=1, b=2)
print(d)
```

```
user@perso-dev:tmp$ python3 -m venv env
user@perso-dev:tmp$ . env/bin/activate
(env) user@perso-dev:tmp$ pip install mypy
Collecting mypy
  Downloading mypy-1.0.1-cp39-cp39-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (18.5 MB)
     |████████████████████████████████| 18.5 MB 12.2 MB/s 
Collecting typing-extensions>=3.10
  Downloading typing_extensions-4.5.0-py3-none-any.whl (27 kB)
Collecting tomli>=1.1.0
  Using cached tomli-2.0.1-py3-none-any.whl (12 kB)
Collecting mypy-extensions>=0.4.3
  Downloading mypy_extensions-1.0.0-py3-none-any.whl (4.7 kB)
Installing collected packages: typing-extensions, tomli, mypy-extensions, mypy
Successfully installed mypy-1.0.1 mypy-extensions-1.0.0 tomli-2.0.1 typing-extensions-4.5.0
(env) user@perso-dev:tmp$ pip install frozendict
Collecting frozendict
  Using cached frozendict-2.3.5-cp39-cp39-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (112 kB)
Installing collected packages: frozendict
Successfully installed frozendict-2.3.5
(env) user@perso-dev:tmp$ mypy foo.py 
foo.py:3: error: Module not callable  [operator]
Found 1 error in 1 file (checked 1 source file)
```

**Comment by Marco-Sulla** [comment] 2023-02-25 23:46
In which directory you are?

**Comment by Marco-Sulla** [comment] 2023-02-26 00:11
Reproducible with Python 3.9, but not with Python 3.10.

**Comment by scottgigante-immunai** [comment] 2023-04-26 13:19
Here's my workaround (tested in python3.8):

```
from typing import TypeVar, Generic
from frozendict import FrozenOrderedDict

FrozenDictKeyT = TypeVar("FrozenDictKeyT")
FrozenDictValueT = TypeVar("FrozenDictValueT")

class FrozenDict(Generic[FrozenDictKeyT, FrozenDictValueT], FrozenOrderedDict):
    pass
```

**Comment by Marco-Sulla** [comment] 2023-04-26 20:04
@scottgigante-immunai please see https://github.com/Marco-Sulla/python-frozendict/pull/70 , it will be merged in minutes.

**Comment by Marco-Sulla** [comment] 2023-04-26 23:37
Well, it seems there were big improvements:

https://github.com/Marco-Sulla/python-frozendict/blob/d5b40fc88fd993f1421099bc753b86c57be562de/src/frozendict/__init__.pyi

Unluckily it's not perfect, and you can see it easily with `mypy test/typed.py`:

* keyword only constructor is not recognized and key type is lost
* subclasses of `frozendict` lose the info about the type of keys and values
* if `frozendict` is contructed from a dict or a seq2, mypy signals that `__or__` returns a dict (that is not true).

Anyway, if nobody is contrary, I think I'll release it when I have time.

**Comment by juliusfrost** [comment] 2023-04-29 18:24
@Marco-Sulla Thanks for the fix! The release would solve some CI issues I'm having :)

**Comment by Marco-Sulla** [comment] 2023-04-29 21:04
`frozendict` 2.3.8 released:

https://github.com/Marco-Sulla/python-frozendict/releases/tag/v2.3.8

I think I can close this issue. For some specific problem about type hints, feel free to open other issues.

PS: what I promise, I'll support.

**Closed by Marco-Sulla** 2023-04-29 21:04 UTC
Labels: Type: Enhancement, Needs: Help, Priority: Low, Needs: Test
