### ISSUE TITLE
[BUG] Testing: object has no attribute 'mapping'

### ISSUE THREAD

**Issue by mtelka** [Marco-Sulla/python-frozendict#73] opened 2023-02-21 23:02 UTC
Welcome! You should write in your Bug Report:

OS version (https://www.google.com/search?channel=fs&q=check+os+version&ie=utf-8&oe=utf-8):
OpenIndiana

Python3 version (python3 -V -V):

Python 3.9.16

Steps to reproduce:

1. python -m pytest --color=no --verbose

Actual result (with the python stack trace if present):

These tests fails:
```
FAILED test/test_frozendict_c_subclass.py::test_mapping_keys - AttributeError...
FAILED test/test_frozendict_c_subclass.py::test_mapping_items - AttributeErro...
FAILED test/test_frozendict_c_subclass.py::test_mapping_values - AttributeErr...
FAILED test/test_frozendict_c.py::test_mapping_items - AttributeError: 'dict_...
FAILED test/test_frozendict_c.py::test_c_extension - AssertionError
FAILED test/test_frozendict_c.py::test_mapping_keys - AttributeError: 'dict_k...
FAILED test/test_frozendict_c.py::test_mapping_values - AttributeError: 'dict...
```

And here are failure details:
```
______________________________ test_mapping_keys _______________________________

fd = F({'Guzzanti': 'Corrado', 'Hicks': 'Bill', F({1: 2}): 'frozen'})

>   ???
E   AttributeError: 'dict_keys' object has no attribute 'mapping'

<string>:367: AttributeError
______________________________ test_mapping_items ______________________________

fd = F({'Guzzanti': 'Corrado', 'Hicks': 'Bill', F({1: 2}): 'frozen'})

>   ???
E   AttributeError: 'dict_items' object has no attribute 'mapping'

<string>:370: AttributeError
_____________________________ test_mapping_values ______________________________

fd = F({'Guzzanti': 'Corrado', 'Hicks': 'Bill', F({1: 2}): 'frozen'})

>   ???
E   AttributeError: 'dict_values' object has no attribute 'mapping'

<string>:373: AttributeError
______________________________ test_mapping_items ______________________________

fd = frozendict.frozendict({'Guzzanti': 'Corrado', 'Hicks': 'Bill', frozendict.frozendict({1: 2}): 'frozen'})

>   ???
E   AttributeError: 'dict_items' object has no attribute 'mapping'

<string>:370: AttributeError
_______________________________ test_c_extension _______________________________

>   ???
E   AssertionError

<string>:2: AssertionError
______________________________ test_mapping_keys _______________________________

fd = frozendict.frozendict({'Guzzanti': 'Corrado', 'Hicks': 'Bill', frozendict.frozendict({1: 2}): 'frozen'})

>   ???
E   AttributeError: 'dict_keys' object has no attribute 'mapping'

<string>:367: AttributeError
_____________________________ test_mapping_values ______________________________

fd = frozendict.frozendict({'Guzzanti': 'Corrado', 'Hicks': 'Bill', frozendict.frozendict({1: 2}): 'frozen'})

>   ???
E   AttributeError: 'dict_values' object has no attribute 'mapping'

<string>:373: AttributeError
```

**Comment by mtelka** [comment] 2023-02-22 15:11
The cause seems to be similar to #74 (`c_ext` is set to `True`).

**Comment by Marco-Sulla** [comment] 2023-02-23 22:36
Dupe of #74

**Closed by Marco-Sulla** 2023-02-23 22:36 UTC
Labels: bug
